### ISSUE TITLE
Novo site, qual caminho seguir?

### ISSUE THREAD

**Issue by naanadr** [pugpe/pyconpe#6]
Foi levantado no grupo do [telegram](t.me/pugpe) o desenvolvimento de uma nova versão do site. Porque a versão atual está em Django 1.4.1 e Python 2.7 :( o que dificulta o desenvolvimento de features novas e correções dos bugs existentes. Outro problema detectado, é a ausência de um deploy automático (o último foi realizado a 8 ANOS ATRÁS). 

Esse papo surgiu após ter sido compartilhado a experiência de organizar e participar de uma sprint online ([Querido Diário - sprint online](https://medium.com/serenata/primeiro-sprint-online-do-projeto-querido-di%C3%A1rio-a6035eba2b)) e talvez fosse possível o PUG-PE também organizar a sua versão de uma sprint online.

Além dessa opção de realizar uma sprint para desenvolver/refatorar o site do PUG-PE, também foi levantado a possibilidade de forkar o repositório [https://github.com/grupyrn/jararaca](https://github.com/grupyrn/jararaca), que contém o código fonte do site do [Grupy-RN](https://meetup.grupyrn.org/). 

Então resumindo... qual caminho devemos seguir? Lembrando que a ideia de fazer uma sprint seria para compartilhar conhecimento, mas para isso seria preciso ter monitores para auxiliar nesse momento, enquanto que forkar o `jararaca` não parece precisar de uma sprint. 

O que vocês acham que seria melhor? E se teria algum problema com a infra que existe hoje (o banco, heroku, enfim, as credencias que precisamos hoje)?

**Comment by Filipelion** [comment]
Gostei bastante da ideia de uma sprint online. Seria uma boa oportunidade para engajar todos da comunidade.
Acredito que o site deva ter uma layout que dê maior destaque aos encontros, onde possamos incluir submissões e visualizar os conteúdos audiovisuais passados.

**Comment by naanadr** [comment]
O sistema atualmente tem submissão de palestra, as pessoas submetem as palestras e elas aparecem para a gente aprovar ou não, as aprovadas ficam na pagina principal do evento. Mas falta essa funcionalidade de anexar o material.

Por enquanto a solução levantada para isso foi esse repositório [encontros-palestras](https://github.com/pugpe/encontros-palestras). Mas não estamos divulgando o bastante, então temos poucas submissões dos conteúdos apresentados pelos palestrantes antigos (eu esqueci de fazer meu PR).

Sobre a sprint, acho que precisa ser levado em consideração alguns pontos:
* Precisa de monitores e por enquanto não vi pessoas se oferecendo para isso, talvez seja melhor fazer uma pré-inscrição pra levantar se há monitores suficiente;
* Vai precisar de um designer? Pra poder fazer o front do site? Ou um template no bootstrap ja seria o suficiente pra gente? (acho que deve ter algum legal por ai);
* Precisamos que @renatooliveira e @fernandogrd nos explique como que faz deploy desse site kkkk (mas acho que isso pode ficar pra depois).

**Comment by cjasm** [comment]
Já houve alguma decisão? Vai desenvolver o projeto?

Acho que se usar Docker evita muito (re)trabalho para o deploy. Inclusive, caso forque o jararaca, poderia complementar com o Docker.

Eu me disponho a ajudar no desenvolvimento e posso mentorar iniciantes também.

**Comment by naanadr** [comment]
Gente, abri a issue no projeto erro. Estou copiando a descrição dessa issue e referênciando ela no lugar certo, vão lá para o https://github.com/pugpe/pugpe/issues/40
